### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by besarthoxhaj** [gazaskygeeks/pasto#37]
@mhmdshorafa could you explain what kind of problem you face on Heroku.

See if I can help

**Comment by mhmdshorafa** [comment]
it works perfect locally but on heroko it opens the google sign page but when you sign in it redirects you to Error: redirect_uri_mismatch look here :" https://pastoo.herokuapp.com/" @besarthoxhaj

**Comment by besarthoxhaj** [comment]
You mean this?

![screen shot 2017-03-05 at 21 41 22](https://cloud.githubusercontent.com/assets/7887496/23590650/957695c8-01ec-11e7-9e63-173e296ff9bd.png)

**Comment by mhmdshorafa** [comment]
yes

**Comment by besarthoxhaj** [comment]
I think it has something to do with google sign in. Usually OAuth requires a callback url and an origin domain from where users sign in.

Try to have a look at the google developer console and see if you find the place where to add https://pastoo.herokuapp.com.

**Comment by besarthoxhaj** [comment]
Will have a look at it and add a section on the README

**Comment by besarthoxhaj** [comment]
Fixed here https://github.com/gazaskygeeks/pasto/pull/39.

The problem was in the google API setup. Notice this part of the documentation: https://developers.google.com/identity/sign-in/web/devconsole-project

> In the **Authorized JavaScript origins** field, enter the origin for your app. You can enter multiple origins to allow for your app to run on different protocols, domains, or subdomains. You cannot use wildcards. In the example below, the second URL could be a production URL.
```
http://localhost:8080
https://myproductionurl.example.com
```
